apiVersion: v1
name: cert-manager
version: 0.1.0
appVersion: v1.12.2
kubeVersion: ">= 1.22.0-0"
description: A Helm chart for cert-manager
sources:
  - https://github.com/cert-manager/cert-manager
dependencies:
  - name: cert-manager
    version: v1.12.2
    repository: https://charts.jetstack.io